server:
  port : 8081
  error:
    include-stacktrace: on_trace_param

pagesize: 10

spring:
  activemq:
    broker-url: tcp://active-mq:61616
    user: admin
    password: admin
  data:
    mongodb:
      host: mongo-db
      port: 27017
      database: Caterer
